### PR TITLE
Merge bed branch to develop branch

### PR DESCRIPTION
**Pull request by JihedC**
Hi all, 
I would like to merge the bed branch to the develop branch. The rules for peak calling seems to work. Could you try on your own side?

There is still a lot of changes and optimisation to do, especially on the method used to defined *treatment* and *control* samples. But it can be done on the develop branch I think.

Cheers,
Jihed

### CODE REVIEW

**Comment by mgalland** [comment]
Hello Jihed. 
In the future, when you ask for tests, maybe it would be wise to specify how snakemake should be run. For instance, if one needs to run `snakemake --use-conda` or simply `snakemake` but then after activating the environment. That's probably why specifying the `--use-conda` is handy in the future (no need to install and activate an environment). 
For now, it's ok, I know my way!

**Comment by JihedC** [comment]
Ok!

**Comment by mgalland** [comment]
For now, I find this mistake:

```
CondaEnvironmentNotFoundError: Could not find environment: macs2 .
You can list all discoverable environments with `conda info --envs`.

    Error in rule call_narrow_peaks:
        jobid: 13
        output: results/bed/ChIP1_vs_ChIP2_L1_peaks.narrowPeak

RuleException:
CalledProcessError in line 267 of /home/mgalland/workspace/DMC1_ChIPseq/Snakefile:
Command ' set -euo pipefail;  
        source activate macs2
        macs2 callpeak -t results/mapped/ChIP1_L1.sorted.rmdup.bam -c results/mapped/ChIP2_L1.sorted.rmdup.bam --format BAMPE --gsize mm --name ChIP1_vs_ChIP2_L1 --nomodel --bdg -q 0.05 --outdir results/bed/ ' returned non-zero exit status 1.
  File "/home/mgalland/workspace/DMC1_ChIPseq/Snakefile", line 267, in __rule_call_narrow_peaks
  File "/home/mgalland/workspace/scripts/miniconda3/envs/DMC1/lib/python3.6/concurrent/futures/thread.py", line 56, in run
```
This has to do with the `source activate macs2` line. This line is not needed if you run snakemake with the `snakemake --use-conda` command provided that you dispose of a `envs/mac2_env.yaml` file.

**Comment by JihedC** [comment]
Make sense, it's only on my computer that I named the environment for macs2 : 'macs2'. I'll change that.
You didn't get an error with another rule?

**Comment by mgalland** [comment]
Only this mistake. I have a hard time working on issue #8 because this issue is in the way.
Instead of merging the `bed branch` to the `develop` branch, I think we need to fix issues #7 and #8

**Pull request merged**
